[project]
name = "grm"
version = "0.3.0"
description = "Manage git repositories"
authors = [
    {name = "Youngwoo Kim",email = "yw.sean.kim@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "rich (>=14.2.0,<15.0.0)",
    "pygit2 (>=1.19.1,<2.0.0)"
]

[project.scripts]
grm = "grm.cli:main"

[tool.poetry]
packages = [{include = "grm", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
